language: ruby
gemfile:
   - Gemfile
rvm:
  - "1.9.3"
script: bundle exec rake test:syntax test:lint test:spec
before_install:
  - sudo apt-get install -y libxslt-dev
  - sudo gem install test-kitchen --pre
  - sudo gem install kitchen-vagrant
  - sudo gem install berkshelf
notifications:
  email:
    - ferre.adrien@gmail.com